### ISSUE TITLE
total property for DVector

### ISSUE THREAD

**Issue by asongtoruin** [Transport-for-the-North/caf.core#24]
Would it be possible to get a `.total` property added to `DVector`? I think it would be as simple as:

```python
@property
def total(self):
    return self.data.sum().sum()
```

This would be super-useful for Land-Use in terms of being able to check the different processing stages, and I'm sure it would have wider use too. We can work around it if needs be, but this just feels as though it would be neater and as far as I can tell nothing similar already exists?

**Comment by isaac-tfn** [comment]
Added to working PR
