### ISSUE TITLE
YAML files not included in pip-install of rewrite_exclusions branch

### ISSUE THREAD

**Issue by asongtoruin** [Transport-for-the-North/caf.core#34]
Mainly fyi @isaac-tfn - I believe the current setup if you do e.g.

```shell
pip install git+https://github.com/Transport-for-the-North/caf.core@rewrite_exclusions
```

does not include the `.yml` files that now define the exclusions. I think you could do this via `tool.setuptools.package-data` in `pyproject.toml`, though I'm not totally sure.

**Comment by isaac-tfn** [comment]
Thanks for raising, for now it does work if you clone the repo and install with a path to the package on your machine rather than a link to the remote repo, but I'll try and fix it properly when I get a chance

**Comment by asongtoruin** [comment]
I've re-tried the same approach with the corrected code and it works now! Thanks Isaac, will close the issue.
