### ISSUE TITLE
"Lookup-only" segmentation throws error

### ISSUE THREAD

**Issue by asongtoruin** [Transport-for-the-North/caf.core#41]
In the current IPF branch (112e00e), if we try to create a `Segmentation` that _solely_ consists of "lookup" segments, like so:

```python
from caf.core.segmentation import Segmentation, SegmentationInput

inp = SegmentationInput(enum_segments=['sic_1_digit', 'sic_2_digit'], naming_order=['sic_1_digit', 'sic_2_digit'])

seg = Segmentation(inp)
seg.ind()
```

We get a:

```
ValueError: Must pass non-zero number of levels/codes
```

This is caused by this section of code:

https://github.com/Transport-for-the-North/caf.core/blob/112e00e422083f61c6fa8bf3ed0e42a764c24e98/src/caf/core/segmentation.py#L221-L223

If we only have "lookup" segments, `prod` is an empty list. We can't create a `MultiIndex` with an empty list. @isaac-tfn can you look at this please? It is preventing us from running the employment code in Land-Use.

**Comment by isaac-tfn** [comment]
Sorry should be fixed now, oversight on segmentations whose segments all lookup each other.

**Comment by asongtoruin** [comment]
Thanks @isaac-tfn that seemed to solve that issue.

Would it be worth adding some "standard segment" checks into the tests? e.g. checking all pairs and triplets from `SegmentsSuper` to ensure they build properly?

**Comment by isaac-tfn** [comment]
Yes that would be a good idea. There are lots of things that should be added to tests that we just don't have time for at the moment unfortunately. I'll add that to the list
