### ISSUE TITLE
SIC Exclusions are the wrong way round

### ISSUE THREAD

**Issue by asongtoruin** [Transport-for-the-North/caf.core#45]
As per the title - to give an example, SIC 2 category 1:

https://github.com/Transport-for-the-North/caf.core/blob/b243fcaa3a281e59ad22cbe4e1947af0be81d373/src/caf/core/segments/sic_2_digit.yml#L4

Is listed as incompatible with SIC 4 categories 1-32

https://github.com/Transport-for-the-North/caf.core/blob/b243fcaa3a281e59ad22cbe4e1947af0be81d373/src/caf/core/segments/sic_2_digit.yml#L99-L133

When in reality these are the **only** SIC 4 categories that are compatible with SIC 2:

https://github.com/Transport-for-the-North/caf.core/blob/b243fcaa3a281e59ad22cbe4e1947af0be81d373/src/caf/core/segments/sic_4_digit.yml#L1-L34

It's worth noting the end of the SIC 4 file states:

https://github.com/Transport-for-the-North/caf.core/blob/b243fcaa3a281e59ad22cbe4e1947af0be81d373/src/caf/core/segments/sic_4_digit.yml#L619-L620

Should this same logic also be applied to SIC 1 and SIC 2?

**Comment by isaac-tfn** [comment]
Hi Adam, these aren't exclusions, but lookups. I didn't rename the argument in the class from 'exclusions' to something more appropriate as it would have meant all of the existing segments needed changing. As for the comment at the end of SIC 4, this is the case for SIC 1 and SIC 2 as well, as in they only have relationships defined with one another, not with other segments too. Are you experiencing issues as a result of the way these are defined or is it just something you noticed when looking at the segment definitions?

**Comment by simonkilbyaecom** [comment]
Hi Isaac, yes we have come across issues when we are combining a DVector with segmentations (sic_4_digit, sic_2_digit)
![image](https://github.com/user-attachments/assets/1736289e-1c7b-4333-b255-e89052f3e2ec)
And segmentations (sic_1_digit, sic_2_digit and soc)
![image](https://github.com/user-attachments/assets/4d184dc5-be98-43b8-9a39-a7015c816fd0)
And this is generating all the combinations between sic_1_digit and sic_4_digit. Such as 1,33. Which shouldn't exist. These are returning NAs when we are attempting to apply the proportions from the first table to the second.

**Comment by isaac-tfn** [comment]
Hi Simon, ok that's actually a separate issue, I've just taken a look and fixed it, will reference this issue in the commit.

**Comment by simonkilbyaecom** [comment]
Thanks that has indeed removed those combinations that shouldn't be there.
